### ISSUE TITLE
Support Structural Variants

### ISSUE THREAD

**Issue by danvk** [hammerlab/varcode#122] opened 2015-09-18 20:12 UTC
For example, [this VCF][1] gives varcode trouble due to the non-sequence things in the `ALT` column:

```
#CHROM  POS     ID      REF     ALT ...
1       959526  xxx     T       <DEL> ...
1       4932289 yyy     A       <DUP:TANDEM> ...
1       8411313 zzz     A       <DUP:TANDEM> ...
...
```

[1]: https://gist.github.com/danvk/1b909a87b0cac5e758b5

**Comment by iskandr** [comment] 2015-09-18 20:15
Duplicate of https://github.com/hammerlab/varcode/issues/123

**Closed by iskandr** 2015-09-18 20:15 UTC
